language: go

go:
  - 1.11
  - master

script:
  - go get github.com/gsamokovarov/assert
  - make test

matrix:
  fast_finish: true
  allow_failures:
    - go: master

env:
  global:
    - GO111MODULE=on
